### ISSUE TITLE
Setup as PV shown negative

### ISSUE THREAD

**Issue by Wursti87** [Telekatz/venus.dbus-modbus-eastron#3]
If setup as PV the production shown as negative and calculation with other PV is incorrect
(Production of Fronius PV is positive)
Possible to change it, to shown also as positive?
thx

**Comment by Telekatz** [comment]
You need to rewire your power meter and swap the input and output.

**Comment by Wursti87** [comment]
I think for victron this will work; but think then i get for my wallbox incorrect values
Will test it end of the month (get proper logs - have to change complete setup)

**Comment by Wursti87** [comment]
For wallbox doesn't matter which is in/out on meter
